doc: pin Jinja2<3.1 to fix sphinx build issue
Problem: Sphinx build on readthedocs fails with

 ImportError: cannot import name 'environmentfilter' from 'jinja2'

According to

  https://github.com/sphinx-doc/sphinx/issues/10291

this is because newer jinja2 is not compatible with sphinx.
Pin Jinja2 to < 3.1 as noted to workaround the issue.